version: '3'

networks:
  creditto_main:
    driver: bridge

services:

  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - creditto_main
    volumes:
      - ./volumes/zookeeper/data:/opt/zookeeper-3.4.6/data
  
    
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - creditto_main
    volumes:
      - ./volumes/kafka/var:/var
      - ./volumes/kafka/kafka:/kafka
      - ./volumes/kafka/run:/run
    depends_on:
      - zookeeper
  
      
  cabin_db:
    image: mysql:8.0.27
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    networks:
      - creditto_main
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sys

      
  creditto_gateway:
    image: creditto_gateway:latest
    build: ./Gateway
    restart: always    
    ports:
      - "5000:5000"
    depends_on:
      - cabin_db
      - kafka
    networks:
      - creditto_main
      
  sql_writer:
    image: sql_writer:latest
    build: ./SqlWriter
    restart: always
    depends_on:
      - cabin_db
      - kafka
    networks:
      - creditto_main
      
  creditto_matcher:
    image: creditto_matcher:latest
    build: ./Matcher
    restart: always
    depends_on:
      - cabin_db
      - kafka
    networks:
      - creditto_main

  sanity_tests_container:
    image: sanity_tests_container:latest
    command: ["pytest", "-v", "-m", "container"]
    build: ./QaService
    networks:
      - creditto_main
    environment:
      - BASE_URL=http://creditto_creditto_gateway_1:5000
      - SQL_HOST=cabin_db
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - WAIT_BEFORE_TIMEOUT=15
      - MYSQL_DB_WARMUP_DELAY=60




