version: '3'


    
services:

  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./volumes/zookeeper/data:/opt/zookeeper-3.4.6/data
  
    
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./volumes/kafka/var:/var
      - ./volumes/kafka/kafka:/kafka
      - ./volumes/kafka/run:/run
    depends_on:
      - zookeeper
  
      
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sys
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456      

      
  creditto_gateway:
    image: creditto_gateway:latest
    ports:
      - "5000:5000"
    depends_on:
      - cabin_db
      - kafka
      
  sql_writer:
    image: sql_writer:latest
    depends_on:
      - cabin_db
      - kafka
