CONFIG_FILE_PATH = "./config.ini"
USERS_TABLE_NAME = 'users'
ROLES_TABLE_NAME = 'roles'
ACTIONS_TABLE_NAME = 'actions'
ACTIONS_BY_ROLES_TABLE_NAME = 'actions_by_roles'
OFFERS_TABLE_NAME = 'offers'
BIDS_TABLE_NAME = 'bids'

PLACE_OFFER = 2
PLACE_BID = 1
VIEW_PRIVATE_BIDS = 5
VIEW_PRIVATE_OFFERS = 6
VIEW_PRIVATE_MATCHES = 7